create table if not exists public.profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  nickname text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint profiles_nickname_length check (char_length(btrim(nickname)) between 2 and 32)
);

create table if not exists public.web_characters (
  user_id uuid not null references auth.users(id) on delete cascade,
  character_id text not null,
  data jsonb not null,
  extras jsonb not null default '{}'::jsonb,
  revision bigint not null default 1,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  updated_by text not null default 'Web',
  primary key (user_id, character_id),
  constraint web_characters_revision_positive check (revision >= 1)
);

create table if not exists public.web_state (
  user_id uuid primary key references auth.users(id) on delete cascade,
  active_character_id text,
  pack_state jsonb not null default '{}'::jsonb,
  revision bigint not null default 1,
  updated_at timestamptz not null default now(),
  updated_by text not null default 'Web',
  constraint web_state_revision_positive check (revision >= 1)
);

create table if not exists public.sync_history (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  character_id text not null,
  revision bigint not null,
  action text not null,
  device text not null,
  changed_at timestamptz not null default now(),
  data jsonb,
  extras jsonb,
  constraint sync_history_action check (action in ('create', 'save', 'force', 'delete'))
);

create index if not exists sync_history_user_changed_idx
  on public.sync_history(user_id, changed_at desc);
create index if not exists sync_history_character_idx
  on public.sync_history(user_id, character_id, revision desc);

alter table public.profiles enable row level security;
alter table public.web_characters enable row level security;
alter table public.web_state enable row level security;
alter table public.sync_history enable row level security;

drop policy if exists profiles_select_own on public.profiles;
create policy profiles_select_own on public.profiles
  for select to authenticated
  using ((select auth.uid()) = user_id);

drop policy if exists web_characters_select_own on public.web_characters;
create policy web_characters_select_own on public.web_characters
  for select to authenticated
  using ((select auth.uid()) = user_id);

drop policy if exists web_state_select_own on public.web_state;
create policy web_state_select_own on public.web_state
  for select to authenticated
  using ((select auth.uid()) = user_id);

drop policy if exists sync_history_select_own on public.sync_history;
create policy sync_history_select_own on public.sync_history
  for select to authenticated
  using ((select auth.uid()) = user_id);

revoke all on public.profiles from anon;
revoke all on public.web_characters from anon;
revoke all on public.web_state from anon;
revoke all on public.sync_history from anon;
grant select on public.profiles, public.web_characters, public.web_state, public.sync_history to authenticated;

create or replace function public.handle_new_fury_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_nickname text;
begin
  v_nickname := btrim(coalesce(new.raw_user_meta_data ->> 'nickname', ''));
  if char_length(v_nickname) < 2 or char_length(v_nickname) > 32 then
    v_nickname := left(coalesce(nullif(split_part(coalesce(new.email, ''), '@', 1), ''), 'Player'), 32);
    if char_length(v_nickname) < 2 then v_nickname := 'Player'; end if;
  end if;

  insert into public.profiles(user_id, nickname)
  values (new.id, v_nickname)
  on conflict (user_id) do nothing;
  return new;
end;
$$;

revoke all on function public.handle_new_fury_user() from public;

drop trigger if exists on_auth_user_created_fury_profile on auth.users;
create trigger on_auth_user_created_fury_profile
after insert on auth.users
for each row execute function public.handle_new_fury_user();

insert into public.profiles(user_id, nickname)
select
  u.id,
  case
    when char_length(btrim(coalesce(u.raw_user_meta_data ->> 'nickname', ''))) between 2 and 32
      then btrim(u.raw_user_meta_data ->> 'nickname')
    else left(coalesce(nullif(split_part(coalesce(u.email, ''), '@', 1), ''), 'Player'), 32)
  end
from auth.users u
on conflict (user_id) do nothing;

-- Preserve the existing first web version, if present.
insert into public.web_characters(user_id, character_id, data, extras, revision, created_at, updated_at, updated_by)
select
  s.user_id,
  c.value ->> 'id',
  c.value,
  '{}'::jsonb,
  greatest(s.revision, 1),
  s.updated_at,
  s.updated_at,
  'Web · legacy'
from public.user_state s
cross join lateral jsonb_array_elements(s.snapshot::jsonb -> 'characters') c(value)
where coalesce(c.value ->> 'id', '') <> ''
on conflict (user_id, character_id) do nothing;

insert into public.web_state(user_id, active_character_id, pack_state, revision, updated_at, updated_by)
select
  s.user_id,
  s.snapshot::jsonb ->> 'activeCharacterId',
  coalesce(s.pack_state, '{}'::jsonb),
  greatest(s.revision, 1),
  s.updated_at,
  'Web · legacy'
from public.user_state s
on conflict (user_id) do nothing;

insert into public.sync_history(user_id, character_id, revision, action, device, changed_at, data, extras)
select c.user_id, c.character_id, c.revision, 'save', c.updated_by, c.updated_at, c.data, c.extras
from public.web_characters c
where not exists (
  select 1 from public.sync_history h
  where h.user_id = c.user_id and h.character_id = c.character_id and h.revision = c.revision
);

